//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.notification.rit.edu/", ConfigurationName="ServiceReference.StudentInformationService")]
    public interface StudentInformationService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getClassSubscriptio" +
            "nRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getClassSubscriptio" +
            "nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.getClassSubscriptionResponse getClassSubscription(WpfClient.ServiceReference.getClassSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getClassSubscriptio" +
            "nRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getClassSubscriptio" +
            "nResponse")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassSubscriptionResponse> getClassSubscriptionAsync(WpfClient.ServiceReference.getClassSubscriptionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getClassEnrollement" +
            "Request", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getClassEnrollement" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.getClassEnrollementResponse getClassEnrollement(WpfClient.ServiceReference.getClassEnrollementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getClassEnrollement" +
            "Request", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getClassEnrollement" +
            "Response")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassEnrollementResponse> getClassEnrollementAsync(WpfClient.ServiceReference.getClassEnrollementRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getStudentEnrolleme" +
            "ntRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getStudentEnrolleme" +
            "ntResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.getStudentEnrollementResponse getStudentEnrollement(WpfClient.ServiceReference.getStudentEnrollementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getStudentEnrolleme" +
            "ntRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getStudentEnrolleme" +
            "ntResponse")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentEnrollementResponse> getStudentEnrollementAsync(WpfClient.ServiceReference.getStudentEnrollementRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getStudentSubscript" +
            "ionRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getStudentSubscript" +
            "ionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.getStudentSubscriptionResponse getStudentSubscription(WpfClient.ServiceReference.getStudentSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getStudentSubscript" +
            "ionRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getStudentSubscript" +
            "ionResponse")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentSubscriptionResponse> getStudentSubscriptionAsync(WpfClient.ServiceReference.getStudentSubscriptionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getClassSchedulesRe" +
            "quest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getClassSchedulesRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.getClassSchedulesResponse getClassSchedules(WpfClient.ServiceReference.getClassSchedulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getClassSchedulesRe" +
            "quest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getClassSchedulesRe" +
            "sponse")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassSchedulesResponse> getClassSchedulesAsync(WpfClient.ServiceReference.getClassSchedulesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getStudentCoursesRe" +
            "quest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getStudentCoursesRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.getStudentCoursesResponse getStudentCourses(WpfClient.ServiceReference.getStudentCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getStudentCoursesRe" +
            "quest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getStudentCoursesRe" +
            "sponse")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentCoursesResponse> getStudentCoursesAsync(WpfClient.ServiceReference.getStudentCoursesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getStudentProfileRe" +
            "quest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getStudentProfileRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.getStudentProfileResponse getStudentProfile(WpfClient.ServiceReference.getStudentProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getStudentProfileRe" +
            "quest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getStudentProfileRe" +
            "sponse")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentProfileResponse> getStudentProfileAsync(WpfClient.ServiceReference.getStudentProfileRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getClassScheduleFor" +
            "TodayRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getClassScheduleFor" +
            "TodayResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.getClassScheduleForTodayResponse getClassScheduleForToday(WpfClient.ServiceReference.getClassScheduleForTodayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/getClassScheduleFor" +
            "TodayRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/getClassScheduleFor" +
            "TodayResponse")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassScheduleForTodayResponse> getClassScheduleForTodayAsync(WpfClient.ServiceReference.getClassScheduleForTodayRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/subscribeRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/subscribeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.subscribeResponse subscribe(WpfClient.ServiceReference.subscribeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/subscribeRequest", ReplyAction="http://service.notification.rit.edu/StudentInformationService/subscribeResponse")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.subscribeResponse> subscribeAsync(WpfClient.ServiceReference.subscribeRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/subscribe2Request", ReplyAction="http://service.notification.rit.edu/StudentInformationService/subscribe2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfClient.ServiceReference.subscribe2Response subscribe2(WpfClient.ServiceReference.subscribe2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.notification.rit.edu/StudentInformationService/subscribe2Request", ReplyAction="http://service.notification.rit.edu/StudentInformationService/subscribe2Response")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.subscribe2Response> subscribe2Async(WpfClient.ServiceReference.subscribe2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.notification.rit.edu/")]
    public partial class student : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string majorField;
        
        private string phoneField;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
                this.RaisePropertyChanged("major");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subscriptionResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.notification.rit.edu/")]
    public abstract partial class response : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.notification.rit.edu/")]
    public partial class subscriptionResponse : response {
        
        private string response1Field;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string response1 {
            get {
                return this.response1Field;
            }
            set {
                this.response1Field = value;
                this.RaisePropertyChanged("response1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subscriptionRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.notification.rit.edu/")]
    public abstract partial class request : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.notification.rit.edu/")]
    public partial class subscriptionRequest : request {
        
        private string classNumberField;
        
        private string studentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string classNumber {
            get {
                return this.classNumberField;
            }
            set {
                this.classNumberField = value;
                this.RaisePropertyChanged("classNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string studentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
                this.RaisePropertyChanged("studentId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.notification.rit.edu/")]
    public partial class course : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string courseNumberField;
        
        private string describtionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string courseNumber {
            get {
                return this.courseNumberField;
            }
            set {
                this.courseNumberField = value;
                this.RaisePropertyChanged("courseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string describtion {
            get {
                return this.describtionField;
            }
            set {
                this.describtionField = value;
                this.RaisePropertyChanged("describtion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.notification.rit.edu/")]
    public partial class classSchedule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classFormatField;
        
        private string classNumberField;
        
        private course courseField;
        
        private string daysField;
        
        private string endTimeField;
        
        private string instructorField;
        
        private string startTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string classFormat {
            get {
                return this.classFormatField;
            }
            set {
                this.classFormatField = value;
                this.RaisePropertyChanged("classFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string classNumber {
            get {
                return this.classNumberField;
            }
            set {
                this.classNumberField = value;
                this.RaisePropertyChanged("classNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public course course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
                this.RaisePropertyChanged("course");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
                this.RaisePropertyChanged("days");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("endTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string instructor {
            get {
                return this.instructorField;
            }
            set {
                this.instructorField = value;
                this.RaisePropertyChanged("instructor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassSubscription", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getClassSubscriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string classNumber;
        
        public getClassSubscriptionRequest() {
        }
        
        public getClassSubscriptionRequest(string classNumber) {
            this.classNumber = classNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassSubscriptionResponse", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getClassSubscriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.student[] @return;
        
        public getClassSubscriptionResponse() {
        }
        
        public getClassSubscriptionResponse(WpfClient.ServiceReference.student[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassEnrollement", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getClassEnrollementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string classNumber;
        
        public getClassEnrollementRequest() {
        }
        
        public getClassEnrollementRequest(string classNumber) {
            this.classNumber = classNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassEnrollementResponse", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getClassEnrollementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.student[] @return;
        
        public getClassEnrollementResponse() {
        }
        
        public getClassEnrollementResponse(WpfClient.ServiceReference.student[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentEnrollement", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getStudentEnrollementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        public getStudentEnrollementRequest() {
        }
        
        public getStudentEnrollementRequest(string uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentEnrollementResponse", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getStudentEnrollementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.classSchedule[] @return;
        
        public getStudentEnrollementResponse() {
        }
        
        public getStudentEnrollementResponse(WpfClient.ServiceReference.classSchedule[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentSubscription", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getStudentSubscriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        public getStudentSubscriptionRequest() {
        }
        
        public getStudentSubscriptionRequest(string uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentSubscriptionResponse", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getStudentSubscriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.classSchedule[] @return;
        
        public getStudentSubscriptionResponse() {
        }
        
        public getStudentSubscriptionResponse(WpfClient.ServiceReference.classSchedule[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassSchedules", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getClassSchedulesRequest {
        
        public getClassSchedulesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassSchedulesResponse", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getClassSchedulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.classSchedule[] @return;
        
        public getClassSchedulesResponse() {
        }
        
        public getClassSchedulesResponse(WpfClient.ServiceReference.classSchedule[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentCourses", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getStudentCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        public getStudentCoursesRequest() {
        }
        
        public getStudentCoursesRequest(string uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentCoursesResponse", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getStudentCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.course[] @return;
        
        public getStudentCoursesResponse() {
        }
        
        public getStudentCoursesResponse(WpfClient.ServiceReference.course[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentProfile", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getStudentProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        public getStudentProfileRequest() {
        }
        
        public getStudentProfileRequest(string uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentProfileResponse", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getStudentProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.student @return;
        
        public getStudentProfileResponse() {
        }
        
        public getStudentProfileResponse(WpfClient.ServiceReference.student @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassScheduleForToday", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getClassScheduleForTodayRequest {
        
        public getClassScheduleForTodayRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClassScheduleForTodayResponse", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class getClassScheduleForTodayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.classSchedule[] @return;
        
        public getClassScheduleForTodayResponse() {
        }
        
        public getClassScheduleForTodayResponse(WpfClient.ServiceReference.classSchedule[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subscribe", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class subscribeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        public WpfClient.ServiceReference.subscriptionRequest subscriptionRequest;
        
        public subscribeRequest() {
        }
        
        public subscribeRequest(WpfClient.ServiceReference.subscriptionRequest subscriptionRequest) {
            this.subscriptionRequest = subscriptionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subscribeResponse", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class subscribeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.subscriptionResponse @return;
        
        public subscribeResponse() {
        }
        
        public subscribeResponse(WpfClient.ServiceReference.subscriptionResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subscribe2", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class subscribe2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cno;
        
        public subscribe2Request() {
        }
        
        public subscribe2Request(string uid, string cno) {
            this.uid = uid;
            this.cno = cno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subscribe2Response", WrapperNamespace="http://service.notification.rit.edu/", IsWrapped=true)]
    public partial class subscribe2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.notification.rit.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfClient.ServiceReference.subscriptionResponse @return;
        
        public subscribe2Response() {
        }
        
        public subscribe2Response(WpfClient.ServiceReference.subscriptionResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentInformationServiceChannel : WpfClient.ServiceReference.StudentInformationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentInformationServiceClient : System.ServiceModel.ClientBase<WpfClient.ServiceReference.StudentInformationService>, WpfClient.ServiceReference.StudentInformationService {
        
        public StudentInformationServiceClient() {
        }
        
        public StudentInformationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentInformationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentInformationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentInformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.getClassSubscriptionResponse WpfClient.ServiceReference.StudentInformationService.getClassSubscription(WpfClient.ServiceReference.getClassSubscriptionRequest request) {
            return base.Channel.getClassSubscription(request);
        }
        
        public WpfClient.ServiceReference.student[] getClassSubscription(string classNumber) {
            WpfClient.ServiceReference.getClassSubscriptionRequest inValue = new WpfClient.ServiceReference.getClassSubscriptionRequest();
            inValue.classNumber = classNumber;
            WpfClient.ServiceReference.getClassSubscriptionResponse retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).getClassSubscription(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassSubscriptionResponse> WpfClient.ServiceReference.StudentInformationService.getClassSubscriptionAsync(WpfClient.ServiceReference.getClassSubscriptionRequest request) {
            return base.Channel.getClassSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassSubscriptionResponse> getClassSubscriptionAsync(string classNumber) {
            WpfClient.ServiceReference.getClassSubscriptionRequest inValue = new WpfClient.ServiceReference.getClassSubscriptionRequest();
            inValue.classNumber = classNumber;
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).getClassSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.getClassEnrollementResponse WpfClient.ServiceReference.StudentInformationService.getClassEnrollement(WpfClient.ServiceReference.getClassEnrollementRequest request) {
            return base.Channel.getClassEnrollement(request);
        }
        
        public WpfClient.ServiceReference.student[] getClassEnrollement(string classNumber) {
            WpfClient.ServiceReference.getClassEnrollementRequest inValue = new WpfClient.ServiceReference.getClassEnrollementRequest();
            inValue.classNumber = classNumber;
            WpfClient.ServiceReference.getClassEnrollementResponse retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).getClassEnrollement(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassEnrollementResponse> WpfClient.ServiceReference.StudentInformationService.getClassEnrollementAsync(WpfClient.ServiceReference.getClassEnrollementRequest request) {
            return base.Channel.getClassEnrollementAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassEnrollementResponse> getClassEnrollementAsync(string classNumber) {
            WpfClient.ServiceReference.getClassEnrollementRequest inValue = new WpfClient.ServiceReference.getClassEnrollementRequest();
            inValue.classNumber = classNumber;
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).getClassEnrollementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.getStudentEnrollementResponse WpfClient.ServiceReference.StudentInformationService.getStudentEnrollement(WpfClient.ServiceReference.getStudentEnrollementRequest request) {
            return base.Channel.getStudentEnrollement(request);
        }
        
        public WpfClient.ServiceReference.classSchedule[] getStudentEnrollement(string uid) {
            WpfClient.ServiceReference.getStudentEnrollementRequest inValue = new WpfClient.ServiceReference.getStudentEnrollementRequest();
            inValue.uid = uid;
            WpfClient.ServiceReference.getStudentEnrollementResponse retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).getStudentEnrollement(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentEnrollementResponse> WpfClient.ServiceReference.StudentInformationService.getStudentEnrollementAsync(WpfClient.ServiceReference.getStudentEnrollementRequest request) {
            return base.Channel.getStudentEnrollementAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentEnrollementResponse> getStudentEnrollementAsync(string uid) {
            WpfClient.ServiceReference.getStudentEnrollementRequest inValue = new WpfClient.ServiceReference.getStudentEnrollementRequest();
            inValue.uid = uid;
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).getStudentEnrollementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.getStudentSubscriptionResponse WpfClient.ServiceReference.StudentInformationService.getStudentSubscription(WpfClient.ServiceReference.getStudentSubscriptionRequest request) {
            return base.Channel.getStudentSubscription(request);
        }
        
        public WpfClient.ServiceReference.classSchedule[] getStudentSubscription(string uid) {
            WpfClient.ServiceReference.getStudentSubscriptionRequest inValue = new WpfClient.ServiceReference.getStudentSubscriptionRequest();
            inValue.uid = uid;
            WpfClient.ServiceReference.getStudentSubscriptionResponse retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).getStudentSubscription(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentSubscriptionResponse> WpfClient.ServiceReference.StudentInformationService.getStudentSubscriptionAsync(WpfClient.ServiceReference.getStudentSubscriptionRequest request) {
            return base.Channel.getStudentSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentSubscriptionResponse> getStudentSubscriptionAsync(string uid) {
            WpfClient.ServiceReference.getStudentSubscriptionRequest inValue = new WpfClient.ServiceReference.getStudentSubscriptionRequest();
            inValue.uid = uid;
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).getStudentSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.getClassSchedulesResponse WpfClient.ServiceReference.StudentInformationService.getClassSchedules(WpfClient.ServiceReference.getClassSchedulesRequest request) {
            return base.Channel.getClassSchedules(request);
        }
        
        public WpfClient.ServiceReference.classSchedule[] getClassSchedules() {
            WpfClient.ServiceReference.getClassSchedulesRequest inValue = new WpfClient.ServiceReference.getClassSchedulesRequest();
            WpfClient.ServiceReference.getClassSchedulesResponse retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).getClassSchedules(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassSchedulesResponse> WpfClient.ServiceReference.StudentInformationService.getClassSchedulesAsync(WpfClient.ServiceReference.getClassSchedulesRequest request) {
            return base.Channel.getClassSchedulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassSchedulesResponse> getClassSchedulesAsync() {
            WpfClient.ServiceReference.getClassSchedulesRequest inValue = new WpfClient.ServiceReference.getClassSchedulesRequest();
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).getClassSchedulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.getStudentCoursesResponse WpfClient.ServiceReference.StudentInformationService.getStudentCourses(WpfClient.ServiceReference.getStudentCoursesRequest request) {
            return base.Channel.getStudentCourses(request);
        }
        
        public WpfClient.ServiceReference.course[] getStudentCourses(string uid) {
            WpfClient.ServiceReference.getStudentCoursesRequest inValue = new WpfClient.ServiceReference.getStudentCoursesRequest();
            inValue.uid = uid;
            WpfClient.ServiceReference.getStudentCoursesResponse retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).getStudentCourses(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentCoursesResponse> WpfClient.ServiceReference.StudentInformationService.getStudentCoursesAsync(WpfClient.ServiceReference.getStudentCoursesRequest request) {
            return base.Channel.getStudentCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentCoursesResponse> getStudentCoursesAsync(string uid) {
            WpfClient.ServiceReference.getStudentCoursesRequest inValue = new WpfClient.ServiceReference.getStudentCoursesRequest();
            inValue.uid = uid;
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).getStudentCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.getStudentProfileResponse WpfClient.ServiceReference.StudentInformationService.getStudentProfile(WpfClient.ServiceReference.getStudentProfileRequest request) {
            return base.Channel.getStudentProfile(request);
        }
        
        public WpfClient.ServiceReference.student getStudentProfile(string uid) {
            WpfClient.ServiceReference.getStudentProfileRequest inValue = new WpfClient.ServiceReference.getStudentProfileRequest();
            inValue.uid = uid;
            WpfClient.ServiceReference.getStudentProfileResponse retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).getStudentProfile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentProfileResponse> WpfClient.ServiceReference.StudentInformationService.getStudentProfileAsync(WpfClient.ServiceReference.getStudentProfileRequest request) {
            return base.Channel.getStudentProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.getStudentProfileResponse> getStudentProfileAsync(string uid) {
            WpfClient.ServiceReference.getStudentProfileRequest inValue = new WpfClient.ServiceReference.getStudentProfileRequest();
            inValue.uid = uid;
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).getStudentProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.getClassScheduleForTodayResponse WpfClient.ServiceReference.StudentInformationService.getClassScheduleForToday(WpfClient.ServiceReference.getClassScheduleForTodayRequest request) {
            return base.Channel.getClassScheduleForToday(request);
        }
        
        public WpfClient.ServiceReference.classSchedule[] getClassScheduleForToday() {
            WpfClient.ServiceReference.getClassScheduleForTodayRequest inValue = new WpfClient.ServiceReference.getClassScheduleForTodayRequest();
            WpfClient.ServiceReference.getClassScheduleForTodayResponse retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).getClassScheduleForToday(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassScheduleForTodayResponse> WpfClient.ServiceReference.StudentInformationService.getClassScheduleForTodayAsync(WpfClient.ServiceReference.getClassScheduleForTodayRequest request) {
            return base.Channel.getClassScheduleForTodayAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.getClassScheduleForTodayResponse> getClassScheduleForTodayAsync() {
            WpfClient.ServiceReference.getClassScheduleForTodayRequest inValue = new WpfClient.ServiceReference.getClassScheduleForTodayRequest();
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).getClassScheduleForTodayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.subscribeResponse WpfClient.ServiceReference.StudentInformationService.subscribe(WpfClient.ServiceReference.subscribeRequest request) {
            return base.Channel.subscribe(request);
        }
        
        public WpfClient.ServiceReference.subscriptionResponse subscribe(WpfClient.ServiceReference.subscriptionRequest subscriptionRequest) {
            WpfClient.ServiceReference.subscribeRequest inValue = new WpfClient.ServiceReference.subscribeRequest();
            inValue.subscriptionRequest = subscriptionRequest;
            WpfClient.ServiceReference.subscribeResponse retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).subscribe(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.subscribeResponse> WpfClient.ServiceReference.StudentInformationService.subscribeAsync(WpfClient.ServiceReference.subscribeRequest request) {
            return base.Channel.subscribeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.subscribeResponse> subscribeAsync(WpfClient.ServiceReference.subscriptionRequest subscriptionRequest) {
            WpfClient.ServiceReference.subscribeRequest inValue = new WpfClient.ServiceReference.subscribeRequest();
            inValue.subscriptionRequest = subscriptionRequest;
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).subscribeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfClient.ServiceReference.subscribe2Response WpfClient.ServiceReference.StudentInformationService.subscribe2(WpfClient.ServiceReference.subscribe2Request request) {
            return base.Channel.subscribe2(request);
        }
        
        public WpfClient.ServiceReference.subscriptionResponse subscribe2(string uid, string cno) {
            WpfClient.ServiceReference.subscribe2Request inValue = new WpfClient.ServiceReference.subscribe2Request();
            inValue.uid = uid;
            inValue.cno = cno;
            WpfClient.ServiceReference.subscribe2Response retVal = ((WpfClient.ServiceReference.StudentInformationService)(this)).subscribe2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfClient.ServiceReference.subscribe2Response> WpfClient.ServiceReference.StudentInformationService.subscribe2Async(WpfClient.ServiceReference.subscribe2Request request) {
            return base.Channel.subscribe2Async(request);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference.subscribe2Response> subscribe2Async(string uid, string cno) {
            WpfClient.ServiceReference.subscribe2Request inValue = new WpfClient.ServiceReference.subscribe2Request();
            inValue.uid = uid;
            inValue.cno = cno;
            return ((WpfClient.ServiceReference.StudentInformationService)(this)).subscribe2Async(inValue);
        }
    }
}
